checks:
    php:
        code_rating: true
        duplication: true
filter:
    excluded_paths:
        - tests/*
build:
    dependencies:
        before:
            - 'rm -f composer.lock'
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override: [php-scrutinizer-run]
