language: php
php:
        - '7.1'
        - '7.2'
        - '7.3'
        - '7.4'
before_script:
  - rm -f composer.lock
  - composer update
notifications:
        email:
                on_success: always
